
# Let's make a game of guess a number game
# At this game computer generates a number
# and a user should guess it!

#########################################
#             Ingredients:              #
#---------------------------------------#
#       from random import randint      #
#                 print()               #
#                 input()               #
#              if-elif-else             #
#                  int()                #
#########################################

# Import random module
from random import randint

if __name__  == "__main__":

    # Print welcomming words
    print('Welcome to my game, you have to guess the number between 1 and 10 randomly generated by the computer')

    # Get a number from user by input() function
    Number_str = input('Try a number between 1 and 10')

    # Convert the user's number to integer (as long as input() returns string)
    Number_int = int(Number_str)

    # Generate random number using randint 
    Number_comp = randint(1,10)
    # Check if user's guess equal to computer's number
    if Number_int == Number_comp :
        # Print to user that the guess is right
        print('Congratulations, your number is right!')
    
    # Check if user's guess is morte than computer's number
    elif Number_int>Number_comp:
        # Print to user that it is more
        print('Your number is bigger than the random one')

    # If it's not equal or more
    else :
        print('Your number is smaller than the random one')
        # Print that it's too small
